[musicbank]
title = "뮤직뱅크"
url = "https://program.naver.com/p/659774/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"

[showmusiccore]
title = "쇼! 음악중심"
url = "https://program.naver.com/p/658837/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"

[inkigayo]
title = "인기가요"
url = "https://program.naver.com/p/658960/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"

[mcountdown]
title = "엠카운트다운"
url = "https://program.naver.com/p/659252/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"

[theshow]
title = "더쇼"
url = "https://program.naver.com/p/3235720/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"

[showchampion]
title = "쇼챔피언"
url = "https://program.naver.com/p/669613/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"

[sketchbook]
title = "유희열의 스케치북"
url = "https://program.naver.com/p/662817/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"

[satfreedom]
title = "불후의 명곡"
url = "https://program.naver.com/p/670142/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"

[mask]
title = "복면가왕"
url = "https://program.naver.com/p/2404757/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"

[amazingsaturday]
title = "놀라운 토요일"
url = "https://program.naver.com/p/7682370/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"

[barada]
title = "바라는 바다"
url = "https://program.naver.com/p/18681490/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"

[girlsplanet999]
title = "걸스플래닛999 소녀대전"
url = "https://program.naver.com/p/17707525/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"
