[musicbank]
title = "뮤직뱅크"
url = "https://program.naver.com/p/659774/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"
onFail = "stale"

[showmusiccore]
title = "쇼! 음악중심"
url = "https://program.naver.com/p/658837/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"
onFail = "stale"

[inkigayo]
title = "인기가요"
url = "https://program.naver.com/p/658960/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"
onFail = "stale"

[mcountdown]
title = "엠카운트다운"
url = "https://program.naver.com/p/659252/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"

[theshow]
title = "더쇼"
url = "https://program.naver.com/p/3235720/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"
onFail = "stale"

[showchampion]
title = "쇼챔피언"
url = "https://program.naver.com/p/669613/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"
onFail = "stale"

[sketchbook]
title = "유희열의 스케치북"
url = "https://program.naver.com/p/662817/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"
onFail = "stale"

[satfreedom]
title = "불후의 명곡"
url = "https://program.naver.com/p/670142/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"
onFail = "stale"

[mask]
title = "복면가왕"
url = "https://program.naver.com/p/2404757/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"

[amazingsaturday]
title = "놀라운 토요일"
url = "https://program.naver.com/p/7682370/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"
onFail = "stale"

[barada]
title = "바라는 바다"
url = "https://program.naver.com/p/18681490/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"
onFail = "stale"

[girlsplanet999]
title = "걸스플래닛999 소녀대전"
url = "https://program.naver.com/p/17707525/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"
onFail = "stale"

[superband2]
title = "슈퍼밴드2"
url = "https://program.naver.com/p/17565456/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"
onFail = "stale"

[streetwomanfighter]
title = "스트릿 우먼 파이터"
url = "https://program.naver.com/p/18923570/clip"
entrySelector = "li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
imageSelector = "img.ClipCard_img__2XgXF"
contentSelector = "span.ClipCard_time__128vc"
waitUntil = "networkidle"
onFail = "stale"

[navertv_streetwomanfighter]
title = "네이버 TV ─ 스트릿 우먼 파이터"
url = "https://tv.naver.com/cjenm.STREETWOMANFIGHTER/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_theater]
title = "네이버 TV ─ 네이버 공연"
url = "https://tv.naver.com/theater/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_now]
title = "네이버TV ─ 네이버 나우"
url = "https://tv.naver.com/nowkr/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"

[navertv_ubcdran]
title = "네이버TV ─ 열린예술무대 뒤란"
url = "https://tv.naver.com/ubcdran/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"
